sudo: required

services:
  - docker

language: go

go:
  - '1.10'

env:
  global:
    - secure: "dJTUkXs8n4urNRKHYEhG+4N/69Gb/8D8cxwuaCmuuMjOsaXKjogovcCpOukFO39qAnYMcuC1O2cBojeX93xdxPDcP+8Lb5q82qwBlCgJa64IDUie3gwpsgb1zJQVaROv4Z/KzJ8FF/fTv7BTltFfpDtveKQgJB4/TTQuHGJC2vZ3YS5XjEaoWWw64jVlYzYAOrIFNJ5KDl7xzIix/hPbP+GKKHxodwizUnyGRI+a/jWDduPwt0JRg733u9WZ3J6sqMvZpq+v322P+2Zv0OVKRTWPJDqLhU5JD1DN3BiP4ldsY63XzJNOJWlvhEubcQ0gOdJiNI8xUFj/VIJspVyKojt/Cl8bY3MFJhzzd4kG0efDWaO2CKd9KlwmZJ46p2FZPBTJ578kpLmov7PHfx6Sza7TmIMBCPOZe8M2gWOXvMz/V36cIGDyMuLP8CpI+UHmR7+/j2EwqmDmP8Iyh+cUv54JyXzj9YFudjAiHlEgWrsFRodPDyTaibFj8WDOSxRXSm72bZRxikcvUQ7kGUlnvveV2+5fDlrDnpaSJhOwBkp8dxDdnTDty33Ek1nW2VL6/5ZbEIYrI1r5rw1Ft/zsWcMDC9/bDhenSSTvFOb5N5gPF6ZZWJVkCBTfHrFO7MF4HppWV3AOW5uGB32NeEcTEmCS0OOfFT9P96SAIjiKyUw="
    - secure: "goz65WutwJSTMJp50uMljXpdGRJ3zwvlt5vvh6c/MuYxSNtSLWxyrfDdYmBwEusCDC3zySn/zkkPt6+EH7garvuX6iL82xxskBKlEawmBftz0gng5QmG7uDxr+PX7c+WhMGqnmeZ/4vOwiv/HzWGGJdYArQAVPgXo2ZFD+qkmNK3YBWlM4P8kAUHgD4DgihtYDbSUqXepYYn8boGcZQgzag3FLJX/063myS/otNAoOouhMCIcvhHPI4qkKeHHvp3FX11h/C2oqxrxCJ6OeY0eVOYiyTa1mMdPLtJ0fUYEtyAlbJPvCSWU56y1W+4xZMIjsnaLDK7EVygAIoLswIEhyOoCE8y20J59ugJmlicqd20faxg8mffCEA4BemJPJkfMDSYWaVVcDL+SnZ8seKjSIuE3zx3UpiGYlMlzRNSEIfThxv9l5Pvx0gMPEAR5bcw/kXcfLdTFYWy0PaPCkt2iZPSYDeRECyfxPKQxM7HWFvrigb9ghn0LPcAzTmxwGGd9LSZg4JpTjKfr/44zOZxrDZWhScD+XnMyDqVLKtoi+E9SbEMxQ8Jv+WczqRsfV8gTZ/SPdzv/yRjodkjGXtAOdibdKjuyJo3nWLaYTZtNtxAPQkwP1L3tyX8pjP6AvKLTYXEuZ9zPUV7S8rUTtDrijSU6GJeNaVN9B81sz25FSg="
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=nocquidant/sconfe
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
